### ISSUE TITLE
While this solution works, it's not the same as creating elements

### ISSUE THREAD

**Issue by Razpudding** [meyadd/js1#5]
https://github.com/meyadd/javascript/blob/065137d9c6808511c93bb66c7fdcf30dd87c561e/Week3/script.js#L7

You're generating an HTML string which you inject/write in the HTML. That's a lot more buggy and messy than using createElement and appendChild. It's not a mistake but I would recommend you to try the other was as it is more Object Oriented approach.

**Comment by meyadd** [comment]
I'v modified the code to use (createElement  , appendChild) istead of HTML injection
