### ISSUE TITLE
Awesome, you essentially made  constructor function!

### ISSUE THREAD

**Issue by Razpudding** [meyadd/js1#6]
https://github.com/meyadd/javascript/blob/065137d9c6808511c93bb66c7fdcf30dd87c561e/Week3/script.js#L19

We expected people to just write each object inside an array but this is a much better solution. Now if you could just write a function called createLlElement(innerText) that you call for each item in the array for assignment 3(and have that use create and append) you could combine the best of both worlds :)

**Comment by meyadd** [comment]
I added createLlElement function
