### ISSUE TITLE
Ah in the end you did use create element and append child :tada:

### ISSUE THREAD

**Issue by Razpudding** [meyadd/js1#8]
https://github.com/meyadd/javascript/blob/065137d9c6808511c93bb66c7fdcf30dd87c561e/Week3/script.js#L78

Good job overall. I really like how you used functions and their return values and even made function calls from within other functions. Pretty awesome 🥇

**Comment by meyadd** [comment]
Thanks for the valuable notes, I've modified my code as you suggested
